language: python
services:
    - mongodb
    - redis-server
sudo: false
branches:
  only:
    - master
    - /^\d\.\d+$/
    - /^\d\.\d+\.\d+(rc\d+|\.dev\d+)?$/
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
    - python: 3.6
      env: TOXENV=docs
install:
  - pip install -U tox twine wheel codecov
script: tox
after_success:
  - codecov
notifications:
  slack:
    rooms:
      - secure: zsDJgHzhPoAIs8OsOiv5wmNsck++hjZljeYAfKh25UwW8X97Rqvq5r9LMlQzIHf2a638AbsubDNeSbrxxu6cFDeeIFngG1EO5mOSWzKr18LM5pFb0GVlImKzZpKgLqKmaD5ATYXnvUaHjEHgO45TzjIsbwo9P4vRU5C/lGYwfdv/J82hP0OUo02HqWGkwpG0aeuzs1bJZKjS/RdHROt0SQpRfVB8hi4HHrQILgliuVcpvIk46FgRB49VmzpAGuQfJtB06gj8o6tL/1JlXQ9/ElrHwEJyGjiyeP/nP8qit+i9TTlHGT9k0s9oYuXWM8OlgKfKE13Mo8fVRaAhVv9DRcwtNpX5M0RtC5bEjCPQIL14ky4ymeSlGchmy37jTKJCNHm4St4CtodCrF5J77h8Gkjx9tkZOhf4Rd8veMMgv/gj8pyt3asJ8PMDvREjF4n4mRPy5SB53anEhrFXE801KOpqb4Ffsjv2DBJmuAId+OmHLs69jHeiwxkBDaeKDr6rpiiKQaZNbDw5KxjEafEtclVmSdprq57Og2SPaCR1TrUu3SVyUjVoWNj6olKS9ALoiDAVLBprbyBsSS9gYwfTlSBNxCsMApQksjmo0/S6n/FwyCvn4AZZVziLVtVxPBY0sUpRBNySkTTrQzpCiEPNmv7tU8d0ZcVI508/WALzIQ0=
cache:
  directories:
    - $HOME/.cache/pip
#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: grammy.jiang
#  password:
#    secure: nUWjH3+9D9I+Xrsz7isjVKpzXwxlJuWFi2OrWCMSilxUNaMrV/4fA0TShmS40TCxTGSasmApjZgZz+Qu93Z9KlHnP2nmBsEXnqtrrCMIhI52wLFdnMcTCNCutzOiKzVSMK/SvEvRP6+fcWRbsE0n0hVwUZc/Lwz4083OXoMQIuMs3NbVD0rAPcHTBthTwabQjSp8WwYv9wZj/pZQ7qYw+QOe+b8XhQIIA10Oy9rAcyaOGASMsbBithKap91ayj2yRqmM6kb+nwi4aEJo/+XwQuncJWleTOy88Rt+YtoYkDxoHopjwBR2RAoevfq0Y1Mjl9e1mssunzQ053qmXfKAFB77Xn99iR0bmwSwwCtyBgoY/Ed5+wywwNdE6tfNB8/pYXg3z6mTmIwqXCQhn2+ORdD5RFn9RZAV4IoR1z8WRKU6clsVF2Msc9QUsj5wUA7LXkBg4HlVJurZurbFh58ViVTO2aNo6c+7fBiBwbm2aupeB+RlL9kCz14pbJcd89H6ViWByE6O9pFlyNcEt28FaKLIuyWAsAsYOPnj74oYuoV2hZ7y0259ncGX0UsDVzPwaJ/NlQsi4yh2d300mRvOSbiELhBZdABbkN+pgGmE1mlqUkY9GHb070JsOavzedzsuEgBLAaWgTAxeDd9LqFfIE7iFLj+U9v9d73ZtKy4VeE=
#  on:
#    branch: master
##    tags: true
#    repo: grammy-jiang/scrapy-cookies
#    condition: "$TOXENV == py36"
